# goreleaser build and release config
checksum:
  name_template: "tvk-plugins-sha256.txt"
  algorithm: sha256

release:
  # If set to auto, will mark the release as not ready for production
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true
