apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ocp-etcd-backup-restore
spec:
  homepage: https://github.com/trilioData/tvk-interop-plugins/blob/main/docs/ocp-etcd-backup-restore/README.md
  shortDescription: Plugin to Install/Configure/Test TVK ocp-etcd-backup-restore
  version: OCP_ETCD_BACKUP_RESTORE_VERSION
  caveats: |
    Curl and Git neeed to be installed on system for Krew index update to work properly
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/trilioData/tvk-interop-plugins/releases/download/OCP_ETCD_BACKUP_RESTORE_VERSION/ocp-etcd-backup-restore.tar.gz
    sha256: OCP_ETCD_BACKUP_RESTORE_TAR_CHECKSUM
    bin: ocp-etcd-backup-restore
    files:
    - from: ocp-etcd-backup-restore/*
      to: .

  description: |
    ocp-etcd-backup-restore plugin is use to take ETCD backup to and perform ETCD restore from TVK target on OCP cluster.
    > Check available flags for ocp-etcd-backup-restore plugin with :-
    kubectl ocp-etcd-backup-restore --help
    --------------------------------------------------------------
    usage: ETCD Backup and restore on Rancher cluster. Available flags: -backup -restore.
       [-h] [-backup] [-restore] [--target-name TARGET_NAME]
       [--target-namespace TARGET_NAMESPACE] --rancher-url RANCHER_URL
       --bearer-token BEARER_TOKEN [--cluster-name CLUSTER_NAME]
       [--log-location LOG_LOC]

    optional arguments:
        -h, --help            show this help message and exit
        -backup
        -restore
        --target-name TARGET_NAME
                        The name of a single datastore on which etcd backup
                        needs to be shared
        --target-namespace TARGET_NAMESPACE
                        Namespace name where the target resides.
        --rancher-url RANCHER_URL
                        Rancher server URL
        --bearer-token BEARER_TOKEN
                        token to access rancher server
        --cluster-name CLUSTER_NAME
                        cluster name if it is not set in kube-system
        --kubeconfig KUBECONFIG
                        if no context is set, please provide kubeconfig file
                        location
        --log-location LOG_LOC
                        Log file name along with path where the logs should be
                        save. default - /tmp/etcd-ocp-backup.log
    -----------------------------------------------------------------------
